### ISSUE TITLE
Something went wrong when uploading a image.

### ISSUE THREAD

**Issue by Rynaro** [volmer/bootsy#202] opened 2016-04-28 12:53 UTC
Hello again guys,
(I don't want to make here a Q&A :sweat_smile:)

When I use a URL upload, my upload works fine, and show to me the uploaded image in gallery. It's ok here.
But when I try to upload a image (from local), the AJAX response sends to me a "Something went wrong". Then, I look in logs and see this behavior.

`Processing by Bootsy::ImagesController#create as JSON
  Parameters: {"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>nil}}}}}}, "image_gallery_id"=>"65"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  Bootsy::ImageGallery Load (0.4ms)  SELECT  "bootsy_image_galleries".* FROM "bootsy_image_galleries" WHERE "bootsy_image_galleries"."id" = $1 LIMIT 1  [["id", 65]]
   (0.2ms)  BEGIN
   (0.2ms)  COMMIT
`

`ActionController::ParameterMissing (param is missing or the value is empty: image):
  actionpack (4.2.6) lib/action_controller/metal/strong_parameters.rb:251:in ```require'
`

I think, the file_field is not sending the right attribute when form commits.

**Comment by volmer** [comment] 2016-04-28 13:07
Can you please provide a sample application that reproduces the error?

**Comment by Rynaro** [comment] 2016-04-28 13:15
What you need exactly?
I will provide to you. :smiley: 

In time, I can explain the structure for you.
I have a `new.html.erb`, with a `render :partial => 'form', :object => @doc, :locals => {:f => f}`, and in _form.html.erb, I have some inputs, and a `f.bootsy_area :body`.
The form is built by `bootstrap_form_for` (I don't know if bootsy have a conflict with this, and partials).

**Comment by volmer** [comment] 2016-04-28 13:19
Basically I need you to generate a new bare-bones Rails application with Bootsy installed in which the same error occurs. This way we can see if the problem is on Bootsy itself or in your current app. Once you have it ready, please share the repo.

**Comment by Rynaro** [comment] 2016-04-28 15:34
Probably is a specific situation in my project, I made a bare-bone Rails app (with a identical gems version), and made a simple Post scaffold, and the Bootsy works fine.
I'll review the code of project, to search this specific situation.
The project in past uses trix editor with fully cloud attachment storage, and for specific needs of company, the local storage is required.

I notice, in a new app, the right params is sended to route, and in (my) project the params is `object Object`

**Comment by volmer** [comment] 2016-04-28 15:49
Really hard to tell without having an app locally. My best bet would be that some random JS you have is interfering on Bootsy's scripts. I would advise you to disable any addition JS files and gems you have one by one until you find the culprit. If, of course, is in fact a problem with your JS.

**Comment by Rynaro** [comment] 2016-04-30 00:24
I've found the problem. In fact, the problem is in remotipart gem files.
In other comment, I've mentioned that the app has a cloud integration. Is the cloud integration files, conflicts with the remotipart AJAX request. When I remove all integration with the cloud (Cloudinary and Attachinary), bootsy works fine. :smiley: 
I don't know, but, I think, it's a good ideia maintain this thread as a knowledge base.

**Comment by volmer** [comment] 2016-04-30 00:26
Good to hear you were able to figure out the problem. I'm closing the issue now but it will still available if anyone ever search about it.

**Closed by volmer** 2016-04-30 00:26 UTC
