### ISSUE TITLE
Bootsy uploads images as needing permission to view image. Can't view image unless I go to AWS and change permission for each file and change URL bootsy generates.

### ISSUE THREAD

**Issue by jleewebdev** [volmer/bootsy#247] opened 2016-12-28 09:11 UTC
I am using rails 4.2.6, bootsy 2.3.1 and AWS. Whenever I upload a images in my WYSIWYG editor and look at the output later, the url to the image is appended with something like this. I've replaced the values with "XXX"

`DOMAIN/public/temp/bootsy/image/20/IMAGE_NAME.jpeg?X-Amz-Algorithm=XXXAmz-Credential=XXXt&X-Amz-Date=X&X-Amz-Expires=XXX0&X-Amz-SignedHeaders=host&X-Amz-Signature=XXX`

The image does not show up and if I enter that url in my search bar, I receive a an XML file with "permission denied" even though the /bootsy/image folder in AWS is set to public. Why is bootsy adding the params in the URL? I just want to show the image from AWS.

I've went into the textarea and removed the params after manually making the folder public in AWS and that fixed the problem, but I shouldn't have to do this manually.

I am also using Carrierwave to upload files in this project for another model that is just an image and I am not having any problem with that.

**Comment by volmer** [comment] 2016-12-28 16:27
Can you provide a sample application that reproduces the error?

**Comment by jleewebdev** [comment] 2016-12-29 06:43
I set up a sample application here. 
https://bootsytest.herokuapp.com/

Under the post I also outputted the raw html from the database. You can see that bootsy adds the additional text.

Here is the corresponding repo
https://github.com/jleewebdev/bootsy_test

**Comment by volmer** [comment] 2016-12-29 14:09
Unfortunately I can't try your app locally since it's not properly configured to upload to S3. But have you tried using `fog` instead of `carrierwave-aws`? Also have you tried it on Rails 5?

**Comment by volmer** [comment] 2017-03-03 17:34
Closing the issue for now. Feel free to reopen it when you're able to provide more info or an app that I can issue locally.

**Closed by volmer** 2017-03-03 17:34 UTC
