### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by vipul30** [volmer/bootsy#124] opened 2015-03-07 16:55 UTC
Hi - I am getting the undefined is not a function when I'm trying to use bootsy.  Here is the code

<%= f.bootsy_area :overview  %>

The error is at this line

bootsy.js

this.editor = this.$el.wysihtml5($.extend(Bootsy.options, this.options)).data('wysihtml5').editor;

Thank you.

**Comment by volmer** [comment] 2015-03-07 19:27
Could you please provide a sample application that reproduces the error? It works fine in my environment.

**Comment by vipul30** [comment] 2015-03-07 20:29
This is part of a large application.  Are there specific files I can send to you?
Thanks,

**Comment by volmer** [comment] 2015-03-07 20:34
You don't need to send me the app you're working on. I'm asking you to create a repo with a simple Rails app that reproduces the problem you're describing, so we can check if this bug is legit or if the problem is your environment.

**Comment by vipul30** [comment] 2015-03-07 22:15
My guess is it most likely has to do with my environment since I'm new to Rails.  Can you pls guide me to where to look to see where the error may be in my environment?  I tried to upload some files here, but it only allows uploading of images.  I'll also see if I can create a new rails app, add the gem, and see what happens.  Do you have a sample rails project I can download and follow the code?

Thanks,

**Comment by driehuis** [comment] 2015-03-07 23:07
You don't need to upload anything to the issue tracker, the best way to get help is to show a simple app in a github repository that reproduces the issue.

Try forking this app on github to get a quick start: https://github.com/driehuis/bootsy-sample . I forked it from another bug report, and it worked to reproduce the issue I had at the time. Check to see that it works for you, before trying to reproduce your issue in your fork.

**Comment by vipul30** [comment] 2015-03-09 03:29
Thanks for the info.  Do I need to use the asset pipeline?  I was having issues using that in my project, so I'm using the asset pipeline.  How would I include the required .js and .css files in my project if I'm not using this?

**Comment by volmer** [comment] 2015-03-09 13:57
@vipul30 Bootsy requires the Asset pipeline in order to properly work. You won't be able to use it if your app doesn't have the Rails asset pipeline.

**Comment by volmer** [comment] 2015-03-25 02:27
I'm closing this for now. Feel free to reopen it if you need further help.

**Closed by volmer** 2015-03-25 02:27 UTC
